### ISSUE TITLE
Source code comments not furry enough

### ISSUE THREAD

**Issue by totallynotsoup** [virejdasani/pythOwO#1]
Title says for itself. Maybe i'll do dome pull requests to fix thi. (anyway why uppercase words for `function` and etc? don't look really python)

**Comment by virejdasani** [comment]
source code comments furry nowo https://github.com/virejdasani/pythOwO/pull/4

keywords are UPPERCASE because there's no syntax highlighting for pythOwO yet, so it makes it easier to differentiate keywords.
