### ISSUE TITLE
I added PythOwO to PyPI, is that allowed?

### ISSUE THREAD

**Issue by Tulip-0333** [virejdasani/pythOwO#48]
I mean, the LISCENCE file says that distribution is allowed... 
Project here: https://pypi.org/project/PythOwO/

**Comment by virejdasani** [comment]
@Tulip-0333 I was looking to do this myself but since you've done it, could you add me as a maintainer in the project too?
My username is `virejdasani` on PyPi.
Thank youwu anyway for doing this because my laptop for some reason wasn't letting me upload to PyPi

**Comment by Tulip-0333** [comment]
@virejdasani I have added you as a maintainer.
![image](https://user-images.githubusercontent.com/93089383/214200582-0dc1fc95-374b-4f9a-83af-817d6a4a1a1f.png)

**Comment by virejdasani** [comment]
Thank youwu a lot for doing this again, I'm gonna add the PyPi page to the README
